services:
  ufw-manager:
    image: mahelbir/ufw-manager:latest
    container_name: ufw-manager
    pid: host
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    restart: "no"
    volumes:
      - ./templates:/usr/local/share/ufw-manager/templates/custom:ro
    command: ["shell"]